# Generated by Django 3.1.13 on 2023-12-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20231205_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.year'),
        ),
    ]
