# Generated by Django 5.1.4 on 2024-12-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_alter_artwork_id_alter_collection_id_alter_year_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
