# Generated by Django 5.1.4 on 2024-12-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_artwork_price_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
