# Generated by Django 5.1.4 on 2024-12-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Создаётся'), (1, 'Оплачен'), (2, 'Доставлен'), (3, 'Подписка')], default=0)),
                ('address', models.TextField(default='Россия, Москва, ул. Мира, дом 666')),
                ('basket_history', models.JSONField(default=dict)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('send_mail_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
